---
title: "p8105_hw6_zg2486"
output: github_document
date: "2024-11-17"
---

```{r include = FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```

# Problem 1


# Problem 2

#### Import and clean dataset.
```{r}
homicide_df = 
  read_csv("./data/homicide-data.csv") %>% 
  filter(victim_age != "Unknown", victim_race != "Unknown", victim_sex != "Unknown" ) %>% 
  mutate(
    city_state = str_c(city, state, sep = ","),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved"),
    victim_age = as.numeric(victim_age)
  ) %>%
  filter(!city_state %in% c("Dallas,TX", "Phoenix,AZ", "Kansas City,MO", "Tulsa,AL")) %>% 
  filter(victim_race %in% c("White", "Black")) 

```

#### GLM for Baltimore,MD.
```{r}
baltimore_model = 
  homicide_df %>% 
  filter(city_state == "Baltimore,MD") %>% 
  mutate(resolved = as.numeric(resolution == "solved")) %>%
  nest(data = -city_state) %>% 
  mutate(
    model = map(data, \(x) glm(resolved ~ victim_age + victim_race + victim_sex, 
                data = x, family = binomial())),
    results = map(model, broom::tidy, conf.int = TRUE)
  ) %>% 
  unnest(results) %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(
    OR = exp(estimate),
    lower_ci = exp(conf.low), 
    upper_ci = exp(conf.high)
  ) %>% 
  select(city_state, OR, lower_ci, upper_ci) 

baltimore_model %>% 
  knitr::kable(digits = 3)


```



