p8105_hw6_zg2486
================

# Problem 1

# Problem 2

#### Import and clean dataset.

``` r
homicide_df = 
  read_csv("./data/homicide-data.csv") %>% 
  filter(victim_age != "Unknown", victim_race != "Unknown", victim_sex != "Unknown" ) %>% 
  mutate(
    city_state = str_c(city, state, sep = ","),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved"),
    victim_age = as.numeric(victim_age)
  ) %>%
  filter(!city_state %in% c("Dallas,TX", "Phoenix,AZ", "Kansas City,MO", "Tulsa,AL")) %>% 
  filter(victim_race %in% c("White", "Black")) 
```

    ## Rows: 52179 Columns: 12
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (9): uid, victim_last, victim_first, victim_race, victim_age, victim_sex...
    ## dbl (3): reported_date, lat, lon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

#### GLM for Baltimore,MD.

``` r
baltimore_model = 
  homicide_df %>% 
  filter(city_state == "Baltimore,MD") %>% 
  mutate(resolved = as.numeric(resolution == "solved")) %>%
  nest(data = -city_state) %>% 
  mutate(
    model = map(data, \(x) glm(resolved ~ victim_age + victim_race + victim_sex, 
                data = x, family = binomial())),
    results = map(model, broom::tidy, conf.int = TRUE)
  ) %>% 
  unnest(results) %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(
    OR = exp(estimate),
    lower_ci = exp(conf.low), 
    upper_ci = exp(conf.high)
  ) %>% 
  select(city_state, OR, lower_ci, upper_ci) 

baltimore_model %>% 
  knitr::kable(digits = 3)
```

| city_state   |    OR | lower_ci | upper_ci |
|:-------------|------:|---------:|---------:|
| Baltimore,MD | 0.426 |    0.324 |    0.558 |

The adjusted odds ratio and 95 CI for solving homicides comparing male
victims to female victims keeping all other variables fixed is 0.426
(95% CI: 0.324, 0.558).

#### Glm for each city.

``` r
each_city_model = 
  homicide_df %>% 
  mutate(resolved = as.numeric(resolution == "solved")) %>%
  nest(data = -city_state) %>% 
  mutate(
    model = map(data, \(x) glm(resolved ~ victim_age + victim_race + victim_sex, 
                data = x, family = binomial())),
    results = map(model, broom::tidy, conf.int = TRUE)
  ) %>% 
  unnest(results) %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(
    OR = exp(estimate),
    lower_ci = exp(conf.low),
    upper_ci = exp(conf.high)
  ) %>% 
  select(city_state, OR, lower_ci, upper_ci) 

each_city_model %>% 
  knitr::kable(digits = )
```

| city_state        |        OR |  lower_ci |  upper_ci |
|:------------------|----------:|----------:|----------:|
| Albuquerque,NM    | 1.7674995 | 0.8247082 | 3.7618597 |
| Atlanta,GA        | 1.0000771 | 0.6803477 | 1.4582575 |
| Baltimore,MD      | 0.4255117 | 0.3241908 | 0.5575508 |
| Baton Rouge,LA    | 0.3814393 | 0.2043481 | 0.6836343 |
| Birmingham,AL     | 0.8700153 | 0.5713814 | 1.3138409 |
| Boston,MA         | 0.6673219 | 0.3508461 | 1.2600381 |
| Buffalo,NY        | 0.5205704 | 0.2884416 | 0.9358300 |
| Charlotte,NC      | 0.8838976 | 0.5507440 | 1.3905954 |
| Chicago,IL        | 0.4100982 | 0.3361233 | 0.5008546 |
| Cincinnati,OH     | 0.3998277 | 0.2313767 | 0.6670456 |
| Columbus,OH       | 0.5324845 | 0.3770457 | 0.7479124 |
| Denver,CO         | 0.4790620 | 0.2327380 | 0.9624974 |
| Detroit,MI        | 0.5823472 | 0.4619454 | 0.7335458 |
| Durham,NC         | 0.8123514 | 0.3824420 | 1.6580169 |
| Fort Worth,TX     | 0.6689803 | 0.3935128 | 1.1211603 |
| Fresno,CA         | 1.3351647 | 0.5672553 | 3.0475080 |
| Houston,TX        | 0.7110264 | 0.5569844 | 0.9057376 |
| Indianapolis,IN   | 0.9187284 | 0.6784616 | 1.2413059 |
| Jacksonville,FL   | 0.7198144 | 0.5359236 | 0.9650986 |
| Las Vegas,NV      | 0.8373078 | 0.6058830 | 1.1510854 |
| Long Beach,CA     | 0.4102163 | 0.1427304 | 1.0241775 |
| Los Angeles,CA    | 0.6618816 | 0.4565014 | 0.9541036 |
| Louisville,KY     | 0.4905546 | 0.3014879 | 0.7836391 |
| Memphis,TN        | 0.7232194 | 0.5261210 | 0.9835973 |
| Miami,FL          | 0.5152379 | 0.3040214 | 0.8734480 |
| Milwaukee,wI      | 0.7271327 | 0.4951325 | 1.0542297 |
| Minneapolis,MN    | 0.9469587 | 0.4759016 | 1.8809745 |
| Nashville,TN      | 1.0342379 | 0.6807452 | 1.5559966 |
| New Orleans,LA    | 0.5849373 | 0.4218807 | 0.8121787 |
| New York,NY       | 0.2623978 | 0.1327512 | 0.4850117 |
| Oakland,CA        | 0.5630819 | 0.3637421 | 0.8671086 |
| Oklahoma City,OK  | 0.9740747 | 0.6228507 | 1.5199721 |
| Omaha,NE          | 0.3824861 | 0.1988357 | 0.7109316 |
| Philadelphia,PA   | 0.4962756 | 0.3760120 | 0.6498797 |
| Pittsburgh,PA     | 0.4307528 | 0.2626022 | 0.6955516 |
| Richmond,VA       | 1.0060520 | 0.4834671 | 1.9936248 |
| San Antonio,TX    | 0.7046200 | 0.3928179 | 1.2382509 |
| Sacramento,CA     | 0.6688418 | 0.3262733 | 1.3143887 |
| Savannah,GA       | 0.8669817 | 0.4185827 | 1.7802453 |
| San Bernardino,CA | 0.5003444 | 0.1655367 | 1.4623977 |
| San Diego,CA      | 0.4130248 | 0.1913527 | 0.8301847 |
| San Francisco,CA  | 0.6075362 | 0.3116925 | 1.1551470 |
| St. Louis,MO      | 0.7031665 | 0.5298505 | 0.9319005 |
| Stockton,CA       | 1.3517273 | 0.6256427 | 2.9941299 |
| Tampa,FL          | 0.8077029 | 0.3395253 | 1.8598834 |
| Tulsa,OK          | 0.9757694 | 0.6090664 | 1.5439356 |
| Washington,DC     | 0.6910490 | 0.4659731 | 1.0135014 |

#### Create a plot that shows the estimated ORs and CIs for each city.

``` r
each_city_plot =
  each_city_model %>% 
  arrange(OR) %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower_ci, ymax = upper_ci)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(
    title = "Estimated ORs and CIs by City",
    x = "city_state",
    y = "Estimated OR with CI"
  )

each_city_plot
```

<img src="p8105_hw6_zg2486_files/figure-gfm/unnamed-chunk-5-1.png" width="90%" />
